### ISSUE TITLE
Peer to peer code review.

### ISSUE THREAD

**Issue by gandradep** [teke85/Leaderboard#2]
Great setup for this upcoming project, everything looks like it is working properly. 👍 .
Here are some ways you could improve the project:

- Don't forget to delete files or folders that won't be part of the final project.
- Whenever a CSS property is used several times, it's good to consider creating a separate class with this property and adding to the elements that need it.
- Consider using eventListener, instead of calling the event on the html files.

**Comment by teke85** [comment]
Hi @gandradep Thank you for the observation I have made changes.
